### ISSUE TITLE
Add make own roles

### ISSUE THREAD

**Issue by Heyter** [gspetrou/TerrortownTwo#1]
Add make own roles.
Example:
local ROLE = ROLE.Register("Maniac")
ROLE.startCredits = 5
ROLE.group = RG_FFA
ROLE.shop = {"weapon_knife", "weapon_axe"}
ROLE.minmaxPly = 8
etc...

**Comment by gspetrou** [comment]
I can definitely implement this but I can’t see a point why. It’d be more appropriate to loop through players at round start and give them whatever special traits your referring to. Either way something like a maniac class is going to simply be a modified Traitor.

**Comment by gspetrou** [comment]
Going to let this PR sit for a few more days before I close it in case you have anything to add, otherwise will close it at the 2 week old mark.

**Comment by Heyter** [comment]
Nope, nothing.
